version: "3.8" # Sélection de la version de Docker Engine

services: # Configuration des services. Chaque service correspondra à un container du cluster
  mongo: # Service de base de donnée
    image: mongo:latest # Sélection de l'image par défaut depuis le registry officiel
    volumes:
      - mongo_data:/var/lib/mongodb # Création du volume persistant qui contiendra la base de donnée
    expose:
      - 27017 # Exposition du port qui sera en écoute et en envois des données
    ports:
      - 27017:27017  # Mappage d'un port de l'hôte Docker avec un port du container
    networks: # Association du service avec des réseaux
      - back-tier
  nodejs: # Service web
    depends_on: # Dépendance de service
      - mongo
    build: ./backend # Build de l'image à partir d'un Dockerfile
    ports:
      - 8080:8080 # Mappage d'un port de l'hôte Docker avec un port du container
    environment: # Initialisation des variables d'environemment dans le conteneur
      PORT: 8080
    networks: # Association du service avec des réseaux
      - front-tier
      - back-tier
  react: # Service applicatif
    build: ./frontend # Build de l'image à partir d'un Dockerfile
    ports:
      - 3000:3000 # Mappage d'un port de l'hôte Docker avec un port du container
    environment: # Initialisation des variables d'environemment dans le conteneur
      PORT: 3000
    networks: # Compartimention du service dans des réseaux
      - front-tier
      
volumes: # Définition des volumes
  mongo_data: {}
  
networks: # Définition des réseaux
  front-tier:
  back-tier: