version: "3.8"

services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/var/lib/mongodb
    expose:
      - 27017
    ports:
      - 27017:27017  
    networks:
      - back-tier
  node:
    depends_on:
      - mongo
    build: ./backend
    ports:
      - 8080:8080
    environment:
      PORT: 8080
    networks:
      - front-tier
      - back-tier
  react:
    build: ./frontend
    ports:
      - 3000:3000
    environment:
      PORT: 3000
    networks:
      - front-tier
      
volumes:
  mongo_data: {}
  
networks:
  front-tier:
  back-tier: