version: "3.8"

services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/var/lib/mongodb
    expose:
      - 27017
    ports:
      - 27017:27017  
  node:
    depends_on:
      - mongo
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
    environment:
      PORT: 8080
      
volumes:
  mongo_data: {}